#!/bin/sh

FILES=$(git diff --name-only --cached --diff-filter=ACMRTUXB | grep .php);

# run phpcs
if [ ! -z "$FILES" ]; then
	printf "Running Code Sniffer Fixer...\n\n"
	vendor/bin/phpcbf $FILES --standard=%s

    printf "\033[0;42;30m   Code fixed   \033[0m\n"
    printf "\033[0;43;30m   Check fixed changes!   \033[0m\n"

	if [ $? -ne 0 ]
	then
		printf "\033[0;41;37m   Fix coding standards before commit!   \033[0m\n"
		exit 1
	fi
fi
